steps:
  # Install Flutter
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/flutter/flutter.git', '-b', 'stable', '--depth', '1', '/workspace/flutter']
    
  # Set Flutter PATH
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export PATH="$PATH:/workspace/flutter/bin"
        flutter doctor -v
        
  # Get dependencies
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export PATH="$PATH:/workspace/flutter/bin"
        flutter pub get
        
  # Run tests
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export PATH="$PATH:/workspace/flutter/bin"
        flutter test
        
  # Build iOS app
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export PATH="$PATH:/workspace/flutter/bin"
        flutter build ios --release --no-codesign
        
  # Build Android app
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export PATH="$PATH:/workspace/flutter/bin"
        flutter build apk --release

# Store build artifacts
artifacts:
  objects:
    location: 'gs://approach-app-builds'
    paths: 
      - 'build/ios/iphoneos/Runner.app/**/*'
      - 'build/app/outputs/flutter-apk/app-release.apk'

# Build timeout
timeout: '1200s'

# Machine type for build
options:
  machineType: 'E2_HIGHCPU_8'
  
# Substitutions for variables
substitutions:
  _PROJECT_ID: 'approach-flutter-app'