name: Build and Deploy Approach App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.6'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
      
    - name: Build iOS (unsigned)
      run: flutter build ios --release --no-codesign
      
    - name: Archive iOS app
      run: |
        cd build/ios/iphoneos
        zip -r Runner.app.zip Runner.app
        
    - name: Upload iOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: build/ios/iphoneos/Runner.app.zip

  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.6'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Android APK
      run: flutter build apk --release
      
    - name: Upload Android artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk

  deploy-to-firebase:
    needs: [build-ios, build-android]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download iOS artifact
      uses: actions/download-artifact@v4
      with:
        name: ios-app
        path: ./artifacts/ios/
        
    - name: Download Android artifact
      uses: actions/download-artifact@v4
      with:
        name: android-apk
        path: ./artifacts/android/
        
    - name: Setup Firebase CLI
      run: |
        npm install -g firebase-tools
        
    - name: Deploy to Firebase App Distribution
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        # Deploy Android APK
        firebase appdistribution:distribute ./artifacts/android/app-release.apk \
          --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} \
          --groups "testers" \
          --release-notes "Automated build from GitHub Actions"